version: '3.8'

services:
  springboot:
    build:
      context: ./authorizer 
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - JWT_SECRET=your_secret_key

  vue:
    build:
      context: ./client-login-micro-main 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - springboot